region                      = "eu-west-2"
project_name                = "website"
vpc_cidr_block              = "10.0.0.0/16"
instance_tenancy            = "default"
pubsub_cidrs                = ["10.0.10.0/24", "10.0.11.0/24"]
ptesub_cidrs                = ["10.0.12.0/24", "10.0.13.0/24"]
internet_gateway            = "website_IGW"
internet_gateway_route_cidr = "0.0.0.0/0"
nat_gateway                 = "website_nat_gateway"
nat_gateway_route_cidr      = "0.0.0.0/0"
instance_type               = "t2.micro"
instance_class              = "db.t2.micro"
ami                         = "ami-08523e156d117cc29"
enable_dns_hostnames        = true
enable_dns_support          = true
engine_version              = "8.0"
engine                      = "mysql"
allocated_storage           = 20
storage_type                = "gp2"
key_name                    = "fella_keypair"
inbound_ports               = [80, 22]