region                      = "us-west-1"
project_name                = "jobasdevops"
vpc_cidr_block              = "10.0.0.0/16"
instance_tenancy            = "default"
pubsub_cidrs                = ["10.0.10.0/24", "10.0.11.0/24"]
ptesub_cidrs                = ["10.0.12.0/24", "10.0.13.0/24"]
internet_gateway            = "devops_IGW"
internet_gateway_route_cidr = "0.0.0.0/0"
nat_gateway                 = "devops_nat_gateway"
nat_gateway_route_cidr      = "0.0.0.0/0"
instance_type               = "t2.micro"
instance_class              = "db.t2.micro"
ami                         = "ami-026257f4f39c28af8"
enable_dns_hostnames        = true
enable_dns_support          = true
engine_version              = "8.0"
engine                      = "mysql"
allocated_storage           = 30
storage_type                = "gp2" 
inbound_ports               = [80, 22]
# key_name                  = "deployer" 